### ISSUE TITLE
Create a script to generate excel file from catalogue

### ISSUE THREAD

**Issue by boos** [usnistgov/mobile-threat-catalogue#124]
A script should be generated to automatically create an excel file from the catalogue.  

------------------------------------------
**Threat ID**:

**Type of Comment**:
G

**Proposed Change**:
A script (python maybe?) should be available to automatically generate an excel file with all the threat listed in the repository. 

**Justification**:
The catalogue is certainly used for educational purpose but can certainly be used as list of threats as part of an risk management task to identify, assess and manage threats.

The availability of a script to derive an excel file will certainly increase the usability of the content.

**Comment by mrdrewkeller** [comment]
Converting back to an excel file has proven difficult due to the multilevel and multivalue data in the catalog. There doesn't seem to be a clean way of handling it. We will continue to look into it, but in the mean time I have created JSON and XML feeds with all of the threats from the catalog. These can be easily consumed and parsed by anybody wishing to pull them in and will be automatically updated as threats get added or changed.
